### ISSUE TITLE
tdigest_query_prep and weighted average

### ISSUE THREAD

**Issue by rzu512** [jcrist/crick#14]
I haven't finished reading the whole `tdigest_stub.c` yet.
When I read the following function, my first instinct was to think that
- `(a.mean * b.weight + b.mean * a.weight) / (a.weight + b.weight)` 
should be:
- `(a.mean * a.weight + b.mean * b.weight) / (a.weight + b.weight)` 

Not sure if that is right.

```c
/// \brief Preparation for computing quantiles or cdf
/// \param T pointer to a t-digest
/// \pre Assume T->centroids is sorted.
CRICK_INLINE void tdigest_query_prep(tdigest_t* T) {
    int i;
    centroid_t a, b;

    tdigest_flush(T);

    // Set merge_centroids[].mean to cumsum of centroids[].weight
    // Set merge_centroids[i - 1].weight to
    //     (a.mean * b.weight + b.mean * a.weight) / (a.weight + b.weight)
    //     where a = centroids[i - 1] and b = centroids[i]
    //     Except for the last merge_centroid, which is set to T-> max
    b = T->centroids[0];
    T->merge_centroids[0].mean = b.weight;

    // Warning: T->merge_centroids[T->last] is not the last element
    for (i = 1; i < T->last + 1; i++) {
        a = b;  // a = centroids[i - 1];
        b = T->centroids[i];

        T->merge_centroids[i].mean = T->merge_centroids[i - 1].mean + b.weight;
        T->merge_centroids[i - 1].weight = (
                a.mean + (b.mean - a.mean) * a.weight / (a.weight + b.weight));
        // This is same as:
        // [a.m * (a.w + b.w) + (b.m - a.m) * a.w] / (a.w + b.w)
        // = (a.m * b.w + b.m * a.w) / (a.w + b.w)
    }

    // The last merge_centroids is treated differently.
    T->merge_centroids[T->last].weight = T->max;
}
```

**Comment by rzu512** [comment]
Algorithm 3 of the [paper](https://github.com/tdunning/t-digest/blob/641646ffa47420c28b17c4ae71e13ffc507deb25/docs/t-digest-paper/histo.pdf) and the java source code ([github link](https://github.com/tdunning/t-digest/blob/641646ffa47420c28b17c4ae71e13ffc507deb25/core/src/main/java/com/tdunning/math/stats/AVLTreeDigest.java#L206)) are using linear interpolation now.

The meaning of m<sub>i</sub> in algorithm 3 seems to be unspecified. I guess it means the i<sup>th</sup> centroid's mean.

**Comment by rzu512** [comment]
the current implementation cannot work with negative weights...

**Comment by jcrist** [comment]
Thanks for the issue. Due to some odd book-keeping this still was correct, but was really not clear. The recent updates to the upstream repo simplified the algorithms in a way that made this easier to do cleanly. The code as of #15 should be easier to follow and see that it's doing a weighted average (although now between the midpoints between centroids instead of at the centroids).

See https://github.com/jcrist/crick/blob/master/crick/tdigest_stubs.c#L302-L317 and https://github.com/jcrist/crick/blob/master/crick/tdigest_stubs.c#L484-L517. Closing.
